stages:
  data_injestion:
    cmd: python src/data/data_injestion.py
    deps:
    - src/data/data_injestion.py
    params:
    - data_injestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python .\src\data\data_preprocessing.py
    deps:
    - .\data\raw\
    - .\src\data\data_preprocessing.py
    outs:
    - .\data\processed
  feature_engineering:
    cmd: python .\src\features\feature_engineering.py
    deps:
    - .\data\processed\
    - .\src\features\feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - .\data\features
  model_building:
    cmd: python .\src\models\model_building.py
    deps:
    - .\data\features\
    - .\src\models\model_building.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python .\src\models\model_evaluation.py
    deps:
    - .\model.pkl
    - .\src\models\model_evaluation.py
    - .\data\features\
    metrics:
    - metrics.json
